
override RIDETURKEY_GPXCOMPARE_LIBMAKEFILE_PATH      = ${CURDIR}/3rdparty/libmakefile
override RIDETURKEY_GPXCOMPARE_3RDPARTY_PATH         = ${CURDIR}/3rdparty
override RIDETURKEY_GPXCOMPARE_3RDPARTY_INSTALL_PATH = ${CURDIR}/3rdparty/install

subdir-y = \
	3rdparty \
	src \
	test

3rdparty_makeflags-y = \
	RIDETURKEY_GPXCOMPARE_LIBMAKEFILE_PATH=${RIDETURKEY_GPXCOMPARE_LIBMAKEFILE_PATH} \
	RIDETURKEY_GPXCOMPARE_3RDPARTY_PATH=${RIDETURKEY_GPXCOMPARE_3RDPARTY_PATH} \
	RIDETURKEY_GPXCOMPARE_3RDPARTY_INSTALL_PATH=${RIDETURKEY_GPXCOMPARE_3RDPARTY_INSTALL_PATH}

src_makeflags-y = \
	RIDETURKEY_GPXCOMPARE_LIBMAKEFILE_PATH=${RIDETURKEY_GPXCOMPARE_LIBMAKEFILE_PATH} \
	RIDETURKEY_GPXCOMPARE_3RDPARTY_PATH=${RIDETURKEY_GPXCOMPARE_3RDPARTY_PATH} \
	RIDETURKEY_GPXCOMPARE_3RDPARTY_INSTALL_PATH=${RIDETURKEY_GPXCOMPARE_3RDPARTY_INSTALL_PATH} \
	QMAKE=${QMAKE}

src_depends-y = \
	3rdparty

test_makeflags-y = \
	RIDETURKEY_GPXCOMPARE_LIBMAKEFILE_PATH=${RIDETURKEY_GPXCOMPARE_LIBMAKEFILE_PATH} \
	RIDETURKEY_GPXCOMPARE_3RDPARTY_PATH=${RIDETURKEY_GPXCOMPARE_3RDPARTY_PATH} \
	RIDETURKEY_GPXCOMPARE_3RDPARTY_INSTALL_PATH=${RIDETURKEY_GPXCOMPARE_3RDPARTY_INSTALL_PATH}

test_depends-y = \
	src

include ${RIDETURKEY_GPXCOMPARE_LIBMAKEFILE_PATH}/Makefile.lib

tests: all
	${Q}+${MAKE} ${test_makeflags-y} -C test tests
