
target-y = \
	dike${target_extension}

dike${target_extension}_files-y = \
	dike.cpp \
	DikePoint.cpp

dike${target_extension}_includes-y += \
	${RIDETURKEY_GPXCOMPARE_3RDPARTY_INSTALL_PATH}/usr/local/include

dist.dir        = ../dist
dist.bin-y      = dike${target_extension}

include ${RIDETURKEY_GPXCOMPARE_LIBMAKEFILE_PATH}/Makefile.lib
